from node:8

workdir /app
run npm install -g nodemon
# run npm install -g express cors http socket.io cheerio request youtube-dl axios mongoose kue
run npm install
add *.js /app/

entrypoint nodemon api.js
