version: "3"
services:
        # The database
        mongo:
                image: mongo
                ports:
                        - "60717:27017"
        # message broker
        redis:
                image: redis
                ports:
                        - "6379:6379"
        # worker for downloading videos
        worker:
                build: ./worker
                depends_on:
                        - endpoint
                links:
                        - redis
                volumes:
                        - storage:/storage
        # API endpoint serving the requests
        endpoint:
                build: ./endpoint
                ports:
                        - "3000:3000"
                        - "3100:3100"
                depends_on:
                        - mongo
                        - redis
                links:
                        - mongo
                        - redis
                volumes:
                        - storage:/storage
        # UI visualizing internal structure of the database
        adminmongo:
                build: ./adminMongo
                ports:
                        - "1234:1234"
                depends_on:
                        - mongo
                links:
                        - mongo
volumes:
        storage:
