version: "3"
services:
        # The reverse proxy
#        traefik:
#                image: traefik
#                ports:
#                        - "3005:80"
#                        - "8081:8080"
#                volumes:
#                        - /var/run/docker.sock:/var/run/docker.sock
#                        - ./traefik.toml:/etc/traefik/traefik.toml
        # The database
        mongo:
                image: mongo
                ports:
                        - "60717:27017"
        # message broker
        redis:
                image: redis
                ports:
                        - "6379:6379"
        # worker for downloading videos
        worker:
                build: .
                depends_on:
                        - endpoint
                links:
                        - redis
                volumes:
                        - storage:/storage
        # API endpoint serving the requests
        endpoint:
                build: ./endpoint
                ports:
                        - "3005:3005"
#                        - "3003:3003"
#                        - "3004:3004"
#                        - "3000:3000"
#                        - "3001:3001"
#                        - "3002:3002"
                        - "3100:3100"
                depends_on:
                        - mongo
                        - redis
                links:
                        - mongo
                        - redis
                volumes:
                        - storage:/storage
        # UI visualizing internal structure of the database
        adminmongo:
                build: ./adminMongo
                ports:
                        - "1234:1234"
                depends_on:
                        - mongo
                links:
                        - mongo
volumes:
        storage:
